## Copyright 2017 Knossos authors, see NOTICE file
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.

import os.path
import json


os.chdir(os.path.join(os.path.dirname(__file__), '..', '..'))


def listdir(path):
    entries = []

    for sub, dirs, files in os.walk(path):
        for name in files:
            entries.append(os.path.relpath(os.path.join(sub, name), '.').replace('\\', '/'))

    entries.sort()
    return entries


def main():
    pyfiles = []
    for fn in os.listdir('knossos'):
        fn = 'knossos/' + fn
        if os.path.isfile(fn) and fn.endswith('.py'):
            pyfiles.append(fn)

    pyfiles.sort()

    with open('file_list.json', 'w', newline='\n') as stream:
        json.dump({
            '#!': "This file is automatically generated. Please don't edit it manually, use tools/common/update_file_list.py.",
            'templates': listdir('html/templates'),
            'images': listdir('html/images'),
            'python': pyfiles,
        }, stream, indent=4, sort_keys=True)


if __name__ == '__main__':
    main()
