# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "knossos-builder"
    config.vm.box = "StefanScherer/windows_10"

	config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../..", "/knossos_src"

    config.vm.provision :shell, inline: "cd /knossos_src/releng/windows; cmd /C provision.bat"
end
