# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "knossos-builder"
    config.vm.box = "windows_10"

    config.vm.synced_folder "../..", "/cygdrive/c/knossos", type: "rsync", rsync__args: ["--verbose", "--archive", "-z", "--copy-links"]
    config.vm.provision :shell, inline: "cd /knossos/releng/windows; cmd /C provision.bat"
end
