# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/install_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ..qt import QtCore, QtGui, QtWidgets


class Ui_InstallUpdateDialog(object):
    def setupUi(self, InstallUpdateDialog):
        InstallUpdateDialog.setObjectName("InstallUpdateDialog")
        InstallUpdateDialog.resize(460, 560)
        InstallUpdateDialog.setModal(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(InstallUpdateDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(InstallUpdateDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setLegacyWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.treeWidget = QtWidgets.QTreeWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setWordWrap(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setDefaultSectionSize(300)
        self.verticalLayout.addWidget(self.treeWidget)
        self.dlSizeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dlSizeLabel.setObjectName("dlSizeLabel")
        self.verticalLayout.addWidget(self.dlSizeLabel)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.notesField = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesField.sizePolicy().hasHeightForWidth())
        self.notesField.setSizePolicy(sizePolicy)
        self.notesField.setReadOnly(True)
        self.notesField.setObjectName("notesField")
        self.verticalLayout_2.addWidget(self.notesField)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(InstallUpdateDialog)
        self.buttonBox.accepted.connect(InstallUpdateDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(InstallUpdateDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InstallUpdateDialog)

    def retranslateUi(self, InstallUpdateDialog):
        _translate = QtCore.QCoreApplication.translate
        InstallUpdateDialog.setWindowTitle(_translate("InstallUpdateDialog", "Update a mod"))
        self.titleLabel.setText(_translate("InstallUpdateDialog", "Update {MOD}?"))
        self.label_2.setText(_translate("InstallUpdateDialog", "<html><head/><body><p><span style=\" font-weight:600;\">This mod has new optional or recommended packages.</span> Please take a look and select the packages you want.</p><p>You can click on any entry to receive more information.</p></body></html>"))
        self.treeWidget.headerItem().setText(0, _translate("InstallUpdateDialog", "Name"))
        self.treeWidget.headerItem().setText(1, _translate("InstallUpdateDialog", "Filesize"))
        self.treeWidget.headerItem().setText(2, _translate("InstallUpdateDialog", "Dev Mode"))
        self.dlSizeLabel.setText(_translate("InstallUpdateDialog", "Download size: {DL_SIZE}"))
        self.label.setText(_translate("InstallUpdateDialog", "Notes:"))
