Vagrant.configure("2") do |config|
  config.vm.define "knossos-builder"

  # config.vm.box = "ramsey/macos-catalina"
  # config.vm.box_version = "1.0.0"

  # config.vm.box = "gobadiah/macos-mojave"
  # config.vm.box_version = "10.14.6"

  config.vm.box = "vagrant-appunite/macos10.13.5"
  config.vm.box_version = "1.0"

  # config.vm.box = "thealanberman/macos-10.13.4"
  # config.vm.box_version = "201805.23.0"

  # config.vm.box = "jhcook/macos-sierra"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../..", "/opt/knossos", group: "wheel", type: "rsync",
  	rsync__args: ["--verbose", "--archive", "-z", "--copy-links", "-u"],
    rsync__exclude: ["dist", "build", "packer", ".vagrant", "node_modules"]

  config.vm.provision :shell, inline: "sudo -Hu vagrant bash /opt/knossos/releng/macos/provision.sh"
end
